theme: jekyll-theme-minimal
title: zeromev
description: Ethereum miners can take money from you by frontrunning and censoring your transactions. Learn about this and the zeromev frontrunning explorer.
markdown: kramdown
logo: images/zm.svg
author: pmcgoohan
url: "http://info.zeromev.org" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
